### PR TITLE
Changing mobile and small max-width to 479px

### PR DESCRIPTION
**Pull request by rhamilto**
so that it matches Bootstrap.  @sg00dwin discovered this bug, where it appeared in the origin-web-console.

Does https://github.com/benjaminapetersen/layout.attrs/blob/master/src/variables.scss#L76 need to be updated, too?

### CODE REVIEW

**Comment by sgoodwin** [comment]
I don't think you meant me.

**Comment by rhamilto** [comment]
Yeah, sorry @sgoodwin.  I meant @sg00dwin.

**Comment by benjaminapetersen** [comment]
Reviewing this now.

**Comment by benjaminapetersen** [comment]
LGTM.

**Pull request merged**
